src/main/java/cz/cvut/fel/projectassign/web/UserController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.projectassign.web;

import cz.cvut.fel.projectassign.daos.HodnoceniDAO;
import cz.cvut.fel.projectassign.model.Hodnoceni;
import cz.cvut.fel.projectassign.model.User;
import cz.cvut.fel.projectassign.model.UserRole;
import cz.cvut.fel.projectassign.services.HodnoceniService;
import cz.cvut.fel.projectassign.services.UserService;
import java.io.IOException;
import java.io.Serializable;
import java.util.Map;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.authentication.encoding.PasswordEncoder;
import org.springframework.security.authentication.encoding.ShaPasswordEncoder;
import org.springframework.stereotype.Component;

/**
 * Třída prezentační vrstvy zajištující zobrazeni dat, zpracování vstupů od
 * uživatelů a volá metody servisní vrstvy. Zabývá se prevážně uživateli.
 *
 * @author Tom
 */
@Component("userController")
@Scope("request")
public class UserController implements Serializable {

    @Autowired
    private HodnoceniDAO hodnoceniDAO;
    @Autowired
    private HodnoceniService hodnoceniService;
    @Autowired
    private UserService userService;
    private String heslo;
    private String heslo2;
    private String oldHeslo;
    private User user ;
    
    public static String REBIND_FORM_DATA = "RFD";

    //<editor-fold defaultstate="collapsed" desc="změna hesla">
    /**
     * Zmení heslo zvolenému uživateli
     */
    public void changePassword(User u) {
        PasswordEncoder encoder = new ShaPasswordEncoder();
        u.setPassword(encoder.encodePassword(u.getPassword(), null));
        //service.update(u);
    }

    /**
     * Zmení heslo aktualnímu uživateli
     */
    public void changePassword() {
        PasswordEncoder encoder = new ShaPasswordEncoder();
        if (userService.getCurrentUser().getPassword().equals(encoder.encodePassword(oldHeslo, null)) && heslo.equals(heslo2)) {

            userService.getCurrentUser().setPassword(encoder.encodePassword(heslo, null));
            //service.update(service.getCurrentUser());
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Heslo bylo úspěšně změneno."));
        } else {

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Špatně zadané původní heslo! "));
        }

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="setters and getters">
    public User getUser() {
        if (user == null) {
            Map<String, String> parameterMap = (Map<String, String>) FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            String id = parameterMap.get("id");

            if (id != null) {
                try {
                    user = userService.findById(Integer.valueOf(id));
                } catch (NumberFormatException e) {
                    return null;
                }
            }
        }
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public User getCurrentUser() {
        return userService.getCurrentUser();
    }

    public String getHeslo() {
        return heslo;
    }

    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }

    public String getHeslo2() {
        return heslo2;
    }

    public void setHeslo2(String heslo2) {
        this.heslo2 = heslo2;
    }

    public String getOldHeslo() {
        return oldHeslo;
    }

    public void setOldHeslo(String oldHeslo) {
        this.oldHeslo = oldHeslo;
    }
    
//    public Hodnoceni getHodnoceni() {
//        hodnoceniDAO.attach(getUser().getHodnoceni());
//        return getUser().getHodnoceni();
//    }

//    public String getHodnoceni() {
//        return getUser().getHodnoceni().getHodnoceni();
//    }
//    
//    public void setHodnoceni(String hodnoceni) {
//        getUser().getHodnoceni().setHodnoceni(hodnoceni);
//    }
    //</editor-fold>

    
    /**
      * aktualizuje hodnoceni
      * @return 
      */
    public String ohodnoceno(){
//      newSearch=true;
//      rebindData();
        hodnoceniService.update(getUser().getHodnoceni());
        
        FacesMessage msg = new FacesMessage("Zadání bylo ohodnoceno.");
        FacesContext.getCurrentInstance().addMessage(null, msg);
        return String.format("userList.xhtml?%s=1&faces-redirect=true", REBIND_FORM_DATA);
     }
    
    public String zpet(){             
      return "userList.xhtml?faces-redirect=true";
     }
    
    public void validateRights() {
        if (getUser() == null || (!getCurrentUser().hasRole(UserRole.TUTOR) && !getCurrentUser().hasRole(UserRole.ADMIN))) {
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            try {
                ec.redirect(ec.getRequestContextPath() + "/index.xhtml");
            } catch (IOException ex) {
                throw new RuntimeException("Page not found", ex);
            }
        }
    }
}

src/main/webapp/staticElements/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">


        <p>Project Assign | Bakalářské práce 2012 | kontakt: kozakto2@fel.cvut.cz | hlášení chyb: passigncvut@gmail.com | verze 3.0</p>

</ui:composition>

src/main/webapp/staticElements/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">


           <div id="logo"> </div>
        <h1 id="webname">Semestrální práce z předmětu <h:outputText value="#{loginController.getSubjectName()}"/></h1>


</ui:composition>

src/main/webapp/staticElements/logout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xhtml PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:sec="http://www.springframework.org/security/tags">


    <h:outputText value=" #{userController.currentUser.userName}"/>

       <p:menubar>    
                <p:menuitem value="logout" url="/j_spring_security_logout" />
             </p:menubar>    
</ui:composition>

src/main/webapp/staticElements/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xhtml PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:sec="http://www.springframework.org/security/tags">


    <p:menubar id="menuBar">  
        <p:menuitem id="test" value="Úvod" url="index.xhtml"  update="messages" />    
        <p:menuitem value="Zadání" url="zadani.xhtml" update="messages" icon="ui-icon ui-icon-star"/> 

        <sec:authorize ifAllGranted="ROLE_USER">
            <p:menuitem value="Moje semestrálka" url="semestralka.xhtml?id=#{userController.currentUser.zadani.id}" update="messages" icon="ui-icon ui-icon-star" disabled="#{zadaniController.semestralkaDisable()}"/> 
            <p:menuitem value="Odevzdat semestrálku" url="uploadSemestralka.xhtml " update="messages" icon="ui-icon ui-icon-star" disabled="#{zadaniController.odevzdatDisable()}"/>
        </sec:authorize>
        <sec:authorize ifAnyGranted="ROLE_ADMIN,ROLE_TUTOR">
            
                
                <p:menuitem value="Studenti"  url="userList.xhtml" />
                <p:menuitem value="Paralelky"  url="paralelka.xhtml" />
          <sec:authorize ifAnyGranted="ROLE_ADMIN">
              
              <p:menuitem value="Technologie"  url="technologie.xhtml" />   
            <p:submenu label="Administrativa">  
                <p:menuitem value="Globální změna hesla"  url="userHeslo.xhtml" update="messages"/>
                <p:menuitem value="Nahrání uživatelů a zadaní"  url="uploadAdmin.xhtml" update="messages"/>
               
            </p:submenu>
        </sec:authorize>
        </sec:authorize>
        <p:menuitem value="Nastavení"  url="nastaveni.xhtml" update="messages" rendered="false"/>
               
        <p:menuitem value="Stránka předmětu" url="https://edux.feld.cvut.cz/courses/A0B36PR1/classification/start" icon="ui-icon ui-icon-home"/>  

    </p:menubar>  


</ui:composition>