src/main/java/cz/cvut/fel/projectassign/model/Hodnoceni.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.projectassign.model;

import cz.cvut.fel.asf.persistence.hibernate.AbstractPersistable;
import javax.persistence.*;

/**
 * Třída mapujíci databázovou tabulku "Hodnoceni"
 * @author Tom
 */
@Entity
@Table(name = "Hodnoceni")
@AttributeOverride(name="id", column=@Column(name="id_Hodnoceni"))
public class Hodnoceni extends AbstractPersistable<Integer> {
    
    public static final String NEHODNOCENO = "Zatím nehodnoceno";

    @Column(name = "hodnoceni", columnDefinition="TEXT")
    private String hodnoceni;
    
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "id_User", insertable = true, updatable = true)
    private User user = null;

    //<editor-fold defaultstate="collapsed" desc="Initialization">
    
    /**
     * @deprecated This constructor is intended for internal use only, do not use it to instantiate the entity.
     */
    @Deprecated
    public Hodnoceni() {
    }

    @SuppressWarnings("LeakingThisInConstructor")
    public Hodnoceni(String hodnoceni, User user) {
        super(true);
        this.hodnoceni = hodnoceni;
        this.user = user;
        user.setHodnoceni(this);
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Fields properties">
    public String getHodnoceni() {
        return hodnoceni;
    }

    public void setHodnoceni(String hodnoceni) {
        this.hodnoceni = hodnoceni;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Associations properties">
    public User getUser() {
        return user;
    }

    protected void setUser(User user) {
        this.user = user;
    }
    //</editor-fold>
}

src/main/java/cz/cvut/fel/projectassign/web/LoginController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.projectassign.web;

import java.io.IOException;
import java.io.Serializable;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import org.springframework.stereotype.Component;

/**
 * Třída prezentační vrstvy zajištující zobrazeni dat, zpracování vstupů od uživatelů
 * a volá metody servisní vrstvy. Zabývá se přihlášením do aplikace. 
 * @author Tom
 */
@Component("loginController")
public class LoginController implements Serializable {

    private String password = "";
    private String userName = "";
    
    public String getSubjectName() {
        return FacesContext.getCurrentInstance().getExternalContext().getInitParameter("projectassign.subjectname");
    }
    
    public String getSubjectCode() {
        return FacesContext.getCurrentInstance().getExternalContext().getInitParameter("projectassign.subjectcode");
    }

    //<editor-fold defaultstate="collapsed" desc="getters and setters">
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="login">
    /**
     * provede login
     * @throws IOException
     * @throws ServletException
     */
    public void login() throws IOException, ServletException {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        RequestDispatcher dispatcher = ((ServletRequest) context.getRequest()).getRequestDispatcher("/j_spring_security_check?j_username=" + getUserName() + "&j_password=" + getPassword());
        dispatcher.forward((ServletRequest) context.getRequest(), (ServletResponse) context.getResponse());
        FacesContext.getCurrentInstance().responseComplete();
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="pomocné metody">
    /**
     * zajistuje nepredvyplneni u logování
     */
    public void reset() {
        password = "";
        userName = "";
       
    }
    //</editor-fold>
}

src/main/java/cz/cvut/fel/projectassign/web/ParalelkaController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.projectassign.web;

import cz.cvut.fel.asf.web.primefaces.AbstractController;
import cz.cvut.fel.projectassign.model.Paralelka;
import cz.cvut.fel.projectassign.model.UserRole;
import cz.cvut.fel.projectassign.services.ParalelkaService;
import cz.cvut.fel.projectassign.services.UserService;
import java.util.Date;
import java.util.Map;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author balikm1
 */
@Component("paralelkaController")
@Scope("request")
public class ParalelkaController extends AbstractController {
    
    @Autowired
    ParalelkaService paralelkaService;
    @Autowired
    UserService userService;
    
    private Paralelka paralelka;
    private Date deadlineVyber;
    
    public Paralelka getParalelka() {
        if (paralelka == null) {
            Map<String, String> parameterMap = (Map<String, String>) FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            String id = parameterMap.get("id");

            if (id != null) {
                try {
                    paralelka = paralelkaService.findById(Integer.valueOf(id));
                } catch (NumberFormatException e) {
                    return null;
                }
            }
        }
        
        return paralelka;
    }

    public void setParalelka(Paralelka paralelka) {
        this.paralelka = paralelka;
    }
    
    public String getParalelkaTime() {
        return paralelkaService.getCasString(getParalelka());
    }
    
    public String getParalelkaDay() {
        return paralelkaService.getDayString(getParalelka());
    }
    
    public Date getDeadlineVyber() {
        return deadlineVyber;
    }

    public void setDeadlineVyber(Date deadlineVyber) {
        this.deadlineVyber = deadlineVyber;
    }
    
    /**
     * upraví zvolenou paralelku
     *
     * @return
     */
    public String update() {
        paralelkaService.update(getParalelka());
        
        FacesMessage msg = new FacesMessage("Paralelka číslo: " + getParalelka().getCisloParalelky() + " byla upravena.");
        FacesContext.getCurrentInstance().addMessage(null, msg);

        return String.format("paralelka.xhtml?%s=1&faces-redirect=true", REBIND_FORM_DATA);
    }
    
    public String back() {
        return "paralelka.xhtml?faces-redirect=true";
    }
    
    public void init() {
        if (getParalelka() == null || (!userService.getCurrentUser().hasRole(UserRole.TUTOR) && !userService.getCurrentUser().hasRole(UserRole.ADMIN))) {
            pageRedirect("/index.xhtml");
        }
    }
}

src/main/java/cz/cvut/fel/projectassign/web/UploadController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.projectassign.web;

import cz.cvut.fel.asf.businesschecks.BusinessCheckException;
import cz.cvut.fel.asf.businesschecks.BusinessCheckSimpleResult;
import cz.cvut.fel.asf.tools.StringHelper;
import cz.cvut.fel.asf.web.primefaces.AbstractController;
import cz.cvut.fel.projectassign.model.Soubor;
import cz.cvut.fel.projectassign.model.Zadani;
import cz.cvut.fel.projectassign.services.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Třída prezentační vrstvy zajištující zobrazeni dat, zpracování vstupů od
 * uživatelů a volá metody servisní vrstvy. Zabývá se prevážně uploadem.
 *
 * @author Tom
 */
@Component("uploadController")
@Scope("singleton")
public class UploadController extends AbstractController {

    @Autowired
    private UserService serviceUser;
    @Autowired
    private ZadaniService serviceZadani;
    @Autowired
    private TechnologieService serviceTech;
    @Autowired
    private SouborService serviceSoubor;
    @Autowired
    private KosHelperService serviceKosHelper;
    public UploadedFile fileToUpload;
    private List<File> fileListPdf;
    private List<File> fileListSql;
    private List<File> fileListSemestralka;
    private List<File> fileListEr;
    private List<File> fileListJavadoc;
    private Soubor.typSoubor typ;
    private String vyberSoubor = "1";
    private String hideSelect = "";
    private String hideUpload = "hidden";
    private String hideGit = "hidden";

    //<editor-fold defaultstate="collapsed" desc="getters file lists">
    public List<File> getFileListPdf() {
        fileListPdf = new ArrayList<File>();
        File f;
        if ((f = serviceSoubor.getFileNew(serviceUser.getCurrentUser(), ".pdf")) != null) {
            fileListPdf.add(f);
        }

        return fileListPdf;
    }

    public List<File> getFileListJavadoc() {
        fileListJavadoc = new ArrayList<File>();
        File f;
        if ((f = serviceSoubor.getFileNew(serviceUser.getCurrentUser(), "jd.zip")) != null) {
            fileListJavadoc.add(f);
        }
        return fileListJavadoc;
    }

    public List<File> getFileListZip() {
        fileListSemestralka = new ArrayList<File>();
        File f;
        if ((f = serviceSoubor.getFileNew(serviceUser.getCurrentUser(), "sp.zip")) != null) {
            fileListSemestralka.add(f);
        }
        return fileListSemestralka;
    }

    public List<File> getFileListSql() {
        fileListSql = new ArrayList<File>();
        File f;
        if ((f = serviceSoubor.getFileNew(serviceUser.getCurrentUser(), ".sql")) != null) {
            fileListSql.add(f);
        }
        return fileListSql;
    }

    public List<File> getFileListEr() {
        fileListEr = new ArrayList<File>();
        File f;
        if ((f = serviceSoubor.getFileNew(serviceUser.getCurrentUser(), ".jpg")) != null) {
            fileListEr.add(f);
        }
        return fileListEr;
    }

    public Soubor.typSoubor getTyp() {
        switch (Integer.valueOf(getVyberSoubor())) {
            case 1:
                typ = Soubor.typSoubor.SEMESTRALKA;
                break;
            case 2:
                typ = Soubor.typSoubor.DOKUMENTACE;
                break;
            case 3:
                typ = Soubor.typSoubor.JAVADOC;
                break;
            case 4:
                typ = Soubor.typSoubor.SQL;
                break;
            case 5:
                typ = Soubor.typSoubor.ER_DIAGRAM;
                break;
            case 6:
                typ = Soubor.typSoubor.GIT;
                break;
        }

        return typ;
    }

    public void setTyp(Soubor.typSoubor typ) {
        this.typ = typ;
    }

    public String getVyberSoubor() {
        return vyberSoubor;
    }

    public void setVyberSoubor(String vyberSoubor) {
        this.vyberSoubor = vyberSoubor;
    }

    public String getHideSelect() {
        return hideSelect;
    }

    public void setHideSelect(String hideSelect) {
        this.hideSelect = hideSelect;
    }

    public String getHideUpload() {
        return hideUpload;
    }

    public void setHideUpload(String hideUpload) {
        this.hideUpload = hideUpload;
    }

    public String getHideGit() {
        return hideGit;
    }

    public void setHideGit(String hideGit) {
        this.hideGit = hideGit;
    }
    
    public String getHideFile() {
        if(hideUpload.equals("")&&hideGit.equals("hidden")){
            return "hidden";
        }
        return "";
    }

    //</editor-fold>
    public UploadedFile getFileToUpload() {
        return this.fileToUpload;
    }

    public void setFileToUpload(UploadedFile file) {

        this.fileToUpload = file;
    }

    //<editor-fold defaultstate="collapsed" desc="upload kos user + paralelka">
    /**
     * vytvoří záznamy ziskané z kosu
     */
    public void uploadKosFile() {
        FacesMessage msg = new FacesMessage("Vytvářím databázovou strukturu.");
        FacesContext.getCurrentInstance().addMessage("neco", msg);
        if (tryExecute(new Runnable() {
            @Override
            public void run() {
                try {
                    serviceKosHelper.parseKosFile(fileToUpload.getInputstream());
                } catch (IOException ex) {
                    Logger.getLogger(UploadController.class.getName()).log(Level.SEVERE, null, ex);
                    new BusinessCheckSimpleResult(false, "Chyba čtení souboru: %s", ex.getMessage()).throwEx();
                } finally {
                    FacesMessage msg = new FacesMessage(String.format("Bylo vytvořeno %d uživatelů.", serviceKosHelper.getUsersCreated()));
                    FacesContext.getCurrentInstance().addMessage("neco", msg);
                }
            }
        })) {
            msg = new FacesMessage("Povedlo se: Uživatelé byli vytvoření.");
            FacesContext.getCurrentInstance().addMessage("neco", msg);
        }
    }

    @Override
    protected void processExecuteErrorMessages(String[] messages) {
        for (String s : messages) {
            FacesMessage msg = new FacesMessage("Chyba: " + s);
            FacesContext.getCurrentInstance().addMessage("neco", msg);
        }
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="upload zadani">
    public void uploadZadani() throws IOException {

        try {
            parseZadani(fileToUpload);
        } catch (Exception ex) {
            Logger.getLogger(UploadController.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void parseZadani(UploadedFile fileUp) throws Exception {

        InputStream in = fileUp.getInputstream();
        StringBuilder sb = new StringBuilder();

        String s = null;
        int c = -1;

        String nazev = null;
        String popis = null;
        boolean isNazev = true;
        boolean isStart = true;

        do {
            c = in.read();
            sb.append((char) c);

            if (isStart && (s = sb.toString()).contains("\r\n")) {
                s = s.substring(0, s.indexOf("\r\n"));
                sb = sb.delete(0, s.length() + 2);
                isStart = false;
            }

            if (isNazev && (s = sb.toString()).contains("\r\n")) {
                s = s.substring(0, s.indexOf("\r\n"));
                sb = sb.delete(0, s.length() + 2);
                nazev = s;
                isNazev = false;

                cistOdradkování(in);
            }
            if ((s = sb.toString()).contains("=================================")) {
                s = s.substring(0, s.indexOf("================================="));
                sb = sb.delete(0, s.length() + 33);
                popis = s;

                cistOdradkování(in);
            }
            if (nazev != null & popis != null) {

                serviceZadani.create(nazev, popis, 1);
                popis = null;
                nazev = null;
                isNazev = true;
                isStart = true;
            }

        } while (c != -1);

    }

    private void cistOdradkování(InputStream in) throws IOException {
        for (int i = 0; i < 2; i++) {
            in.read();
        }

    }

    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="upload semestralky">
    /**
     * nahraje semestrální práci
     *
     * @param event
     * @return
     */
    public String uploadSemestralka(FileUploadEvent event) {

        serviceSoubor.uploadSemestralky(event, serviceUser.getCurrentUser(), getTyp());
        hideSelect = "";
        hideUpload = "hidden";
        return "uploadSemestralka.xhtml?faces-redirect=true";
    }

    public String checkTypes() {
        String omezeni = "";
        switch (Integer.valueOf(getVyberSoubor())) {
            case 1:
                omezeni = "(.zip)";
                break;
            case 2:
                omezeni = "(.pdf)";
                break;
            case 3:
                omezeni = "(.zip)";
                break;
            case 4:
                omezeni = "(.sql)";
                break;
            case 5:

src/main/webapp/createTechnologie.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:sec="http://www.springframework.org/security/tags">




    <ui:define name="content">

        <sec:authorize ifNotGranted="ROLE_ADMIN,ROLE_TUTOR">
            <p>Nemáte dostatečné oprávnení na zobrazení této stránky</p>
        </sec:authorize>


        <sec:authorize ifAnyGranted="ROLE_ADMIN,ROLE_TUTOR">
            
            <p:breadCrumb>  
                <p:menuitem value="Home" url="index.xhtml" /> 
                <p:menuitem value="Technologie"  url="technologie.xhtml" />
                <p:menuitem value="Tvorba nové technologie" /> 
            </p:breadCrumb>

   <p:messages autoUpdate="true" redisplay="false"/>  
            <h:panelGrid columns="2" cellpadding="2" border="0" id="createZadani" >

              
                <h:outputLabel for="tbNazev" value="Název"/>
                <h:inputText id="tbNazev" value="#{technologieController.technologie ne null ? technologieController.technologie.nazev : technologieController.nazev}" validatorMessage="Délka názvu technologie musí být minimálně 2 znaky a maximalně 128!">
                    <f:validateLength maximum="128" minimum="2"/>
                </h:inputText>

            </h:panelGrid>    

            <p:commandButton type="submit" value="Vytvořit technologii" action="#{technologieController.add()}" >
                <f:param name="id" value="#{param['id']}" />
            </p:commandButton>
            <p:commandButton type="submit" value="Zpět" immediate="true" action="#{technologieController.back()}" />

        </sec:authorize>  

    </ui:define>
</ui:composition>

src/main/webapp/editParalelka.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:sec="http://www.springframework.org/security/tags">

    <ui:define name="content">

        <sec:authorize ifNotGranted="ROLE_ADMIN,ROLE_TUTOR">
            <p>Nemáte dostatečné oprávnení na zobrazení této stránky</p>
        </sec:authorize>

        <sec:authorize ifAnyGranted="ROLE_ADMIN,ROLE_TUTOR">
            <p:breadCrumb>  
                <p:menuitem value="Home" url="index.xhtml" /> 
                <p:menuitem value="Paralelka"  url="paralelka.xhtml" />
                <p:menuitem value="Editování paralelky "/> 
            </p:breadCrumb>


            <f:metadata>
                <f:event type="preRenderView" listener="#{paralelkaController.init()}"/>
            </f:metadata>


            <h:panelGrid columns="2" cellpadding="2" border="0" >
                <h:outputLabel for="tbCisloParalelky" value="Číslo"/>
                <h:outputText id="tbCisloParalelky" value="#{paralelkaController.paralelka.cisloParalelky}"  ></h:outputText>

                <h:outputLabel for="tbTime" value="Čas"/>
                <h:outputText id="tbTime" value="#{paralelkaController.paralelkaTime}"/>

                <h:outputLabel for="tbDay" value="Den"/>
                <h:outputText id="tbDay" value="#{paralelkaController.paralelkaDay}"/>

                <h:outputLabel for="calDeadline" value="Deadline výběru"/>
                <p:calendar id="calDeadline" value="#{paralelkaController.paralelka ne null ? paralelkaController.paralelka.deadlineVyber : paralelkaController.deadlineVyber}" pattern="MM/dd/yyyy HH:mm" />

         
            </h:panelGrid>
            <p:commandButton type="submit" value="Uložit" action="#{paralelkaController.update()}" >
             <f:param name="id" value="#{param['id']}" />
            </p:commandButton>
            <p:commandButton type="submit" value="Zpět" immediate="true" action="#{paralelkaController.back()}" />

        </sec:authorize>
    </ui:define>
</ui:composition>

src/main/webapp/uploadSemestralka.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:sec="http://www.springframework.org/security/tags">

    <ui:define name="content">  

        <sec:authorize ifNotGranted="ROLE_USER,ROLE_ADMIN,ROLE_TUTOR">
            <p>Nemáte dostatečné oprávnení na zobrazení této stránky</p>
        </sec:authorize> 

        <sec:authorize ifAnyGranted="ROLE_ADMIN,ROLE_TUTOR">
            <p>Zde student nahrává své soubory, které jsou nutné k odevzdání semestrálky</p>
        </sec:authorize>  

        <sec:authorize ifAllGranted="ROLE_USER">
            <h1>Nahraní Semestrálky</h1>

            <p>Zde nahrajte soubory své semestrální práce. Použijte správnou příponou: semetralní projekt - kod (zip),dokumentace (pdf) a javadoc (zip). Pokud vytváříte databázi je třeba ještě nahrát sql skript(.sql) a er diagram (.jpg). V seznamu se zobrazí se pouze poslední nahraný soubor v kategorii(ale ukládají se všechny). Nějdříve zvolte typ souboru, který chcete nahrát a poté přes tlačítko "Choose" soubor vyberte. </p>

            <div hidden="#{uploadController.hideSelect}">
                <p:selectOneMenu id="select" value="#{uploadController.vyberSoubor}" > 
                    <f:selectItem itemLabel="Semestrálka (zip)  " itemValue="1" />  
                    <f:selectItem itemLabel="Dokumentace (pdf)   " itemValue="2" />  
                    <f:selectItem itemLabel="Javadoc (zip)   " itemValue="3" />
                    <div hidden="#{uploadController.haveSql()}">
                        <f:selectItem itemLabel="SQL skript (sql)  " itemValue="4" />  
                        <f:selectItem itemLabel="ER-diagram (jpg)  " itemValue="5" />  
                    </div>
                </p:selectOneMenu>

                <p:commandButton type="submit" value="Zvolit typ" action="#{uploadController.showUpload()}" ></p:commandButton>


            </div>
          
              
            <div id="showupload" hidden="#{uploadController.hideUpload}">
                <p:panel>
                <h:outputText value="Zvolili jste typ souboru k nahrání: #{uploadController.typ} "/>
                
                <p:commandButton type="submit" value="Změnit typ souboru" action="#{uploadController.showSelectTypes()}" ></p:commandButton>
                <br/>
 
                </p:panel>
                <p>Kliknete na choose a zvolte soubor, který chcete nahrát</p>
              
                <div hidden="#{uploadController.hideFile}">
                <p:fileUpload  id="fileUpload" showButtons="false" multiple="false"  fileUploadListener="#{uploadController.uploadSemestralka}"  mode="advance"
                               sizeLimit="40000000" invalidFileMessage="Nesprávný formát" update="select,uploadHTML,uploadPdf,uploadZip,uploadSQL,uploadSQL2" widgetVar="uploader"  
                               allowTypes="#{uploadController.checkTypes()}">

                </p:fileUpload>
                </div>
                <div hidden="#{uploadController.hideGit}">
                </div>
              
            </div>
            
            
            <p:messages  showDetail="true" autoUpdate="true" redisplay="false"/>  


            <br/>
            <p:dataTable id="uploadPdf" value="#{uploadController.fileListPdf}" var="file" emptyMessage="Nenalezena žádná data - pro úspěšné odevzdání semestrální práce je potřeba nahrát všechny části.">

                <p:column>   
                    <f:facet name="header">
                        <h:outputText value="dokumentace: pdf" />
                    </f:facet>
                    <p:commandLink id="downloadLink" value="#{downloadController.getPuvJmeno(file)}" ajax="false" >  
                        <p:fileDownload value="#{downloadController.download(file)}" />  
                    </p:commandLink>                   
                </p:column>

            </p:dataTable>

            <br/>
            <p:dataTable id="uploadHTML" value="#{uploadController.fileListJavadoc}" var="file" emptyMessage="Nenalezena žádná data - pro úspěšné odevzdání semestrální práce je potřeba nahrát všechny části">

                <p:column>   
                    <f:facet name="header">
                        <h:outputText value="Javadoc : zip" />
                    </f:facet>
                    <p:commandLink id="downloadLink" value="#{downloadController.getPuvJmeno(file)}" ajax="false">  
                        <p:fileDownload value="#{downloadController.download(file)}" />  
                    </p:commandLink>                   
                </p:column>

            </p:dataTable>
            <br/>
            <p:dataTable id="uploadZip" value="#{uploadController.fileListZip}" var="file" emptyMessage="Nenalezena žádná data - pro úspěšné odevzdání semestrální práce je potřeba nahrát všechny části">

                <p:column>     
                    <f:facet name="header">
                        <h:outputText value="Semestrálka: .zip" />
                    </f:facet>
                    <p:commandLink id="downloadLink" value="#{downloadController.getPuvJmeno(file)}" ajax="false">  
                        <p:fileDownload value="#{downloadController.download(file)}" />  
                    </p:commandLink>                   
                </p:column>

            </p:dataTable>

            <br/>
            <div hidden="#{uploadController.haveSql()}">
                <p:dataTable id="uploadSQL" value="#{uploadController.fileListSql}" var="file" emptyMessage="Nenalezena žádná data - pro úspěšné odevzdání semestrální práce je potřeba nahrát všechny části">

                    <p:column>     
                        <f:facet name="header">
                            <h:outputText value="SQL - .sql" />
                        </f:facet>
                        <p:commandLink id="downloadLink" value="#{downloadController.getPuvJmeno(file)}" ajax="false">  
                            <p:fileDownload value="#{downloadController.download(file)}" />  
                        </p:commandLink>                   
                    </p:column>
                </p:dataTable>

                <br/>

                <p:dataTable id="uploadSQL2" value="#{uploadController.fileListEr}" var="file" emptyMessage="Nenalezena žádná data - pro úspěšné odevzdání semestrální práce je potřeba nahrát všechny části">

                    <p:column>     
                        <f:facet name="header">
                            <h:outputText value="ER-diagram - .jpg" />
                        </f:facet>
                        <p:commandLink id="downloadLink" value="#{downloadController.getPuvJmeno(file)}" ajax="false">  
                            <p:fileDownload value="#{downloadController.download(file)}" />  
                        </p:commandLink>                   
                    </p:column>

                </p:dataTable>   


            </div>
            <p></p>
        </sec:authorize>
    </ui:define>
</ui:composition>